<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- 메모리 복사 최소화를 위해 포인터 캐스팅 허용 -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <!-- SQLite 드라이버 -->
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.12" />
    <!-- SIMD 가속 하드웨어 연산을 위한 Tensor 패키지 -->
    <PackageReference Include="System.Numerics.Tensors" Version="9.0.0" />
  </ItemGroup>

</Project>
